# Generated by Django 3.1.7 on 2021-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_horario_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='tipo',
            field=models.CharField(choices=[('D', 'DUPLO'), ('U', 'ÚNICO')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('T', 'TARDE'), ('M', 'MANHÃ')], max_length=50),
        ),
    ]
