# Generated by Django 3.1.7 on 2021-04-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210403_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='tipo',
            field=models.CharField(choices=[('D', 'DUPLO'), ('U', 'ÚNICO')], default='U', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('M', 'MANHÃ'), ('T', 'TARDE')], default='M', max_length=50),
        ),
    ]
