# Generated by Django 3.1.7 on 2021-04-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210403_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='turno',
            field=models.CharField(choices=[('T', 'TARDE'), ('M', 'MANHÃ')], default='M', max_length=50),
        ),
    ]
